plugins {
    id 'java'
    id 'maven-publish'
    id 'signing'
    id 'org.jetbrains.kotlin.jvm'
}

group = 'com.cabin.express'
version = '26.0.0' // remove "v" prefix, Maven Central prefers semantic version numbers

java {
    withJavadocJar()
    withSourcesJar()
}

repositories {
    mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java

            groupId = 'com.cabin.express'
            artifactId = 'cabinj'
            version = '26.0.0'

            pom {
                name.set("CabinJv")
                description.set("CabinJv is a light weight web framework for Java")
                url.set("https://github.com/CabinJV/CabinJv")

                licenses {
                    license {
                        name.set("The Apache License, Version 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0.txt")
                    }
                }

                developers {
                    developer {
                        id.set("cabin")
                        name.set("Sang Le")
                        email.set("sang.sevn@gmail.com")
                    }
                }

                scm {
                    connection.set("scm:git:https://github.com/CabinJV/CabinJv.git")
                    developerConnection.set("scm:git:ssh://github.com/CabinJV/CabinJv.git")
                    url.set("https://github.com/CabinJV/CabinJv")
                }
            }
        }
    }

    repositories {
        maven {
            name = "OSSRH"
            url = uri(
                    version.endsWith("SNAPSHOT")
                            ? "https://s01.oss.sonatype.org/content/repositories/snapshots/"
                            : "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"
            )

            credentials {
                username = project.findProperty("ossrhUsername") ?: System.getenv("OSSRH_USERNAME")
                password = project.findProperty("ossrhPassword") ?: System.getenv("OSSRH_PASSWORD")
            }
        }
    }
}

signing {
    sign publishing.publications.mavenJava
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'ch.qos.logback:logback-classic:1.4.5'
    implementation 'org.slf4j:slf4j-api:2.0.9'

    implementation 'org.apache.httpcomponents.client5:httpclient5:5.4.4'
    implementation 'org.apache.httpcomponents.core5:httpcore5:5.3.4'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.0'
    testImplementation 'org.assertj:assertj-core:3.27.3'
    testImplementation 'org.mockito:mockito-core:5.4.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.14.2'
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
}

test {
    useJUnitPlatform()
}

task copyDependencies(type: Copy) {
    from configurations.runtimeClasspath
    into "$buildDir/libs/libs"
}

jar {
    dependsOn copyDependencies
    manifest {
        attributes(
                'Gradle-Version': gradle.gradleVersion,
                'Created-By': System.getProperty("java.version") + " (Java)",
                'Class-Path': configurations.runtimeClasspath.files.collect { "libs/" + it.name }.join(' '),
                'Main-Class': 'examples.sample.HServer'
        )
    }
    archiveBaseName.set('cabin')
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE

    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
