version: '3.8'

services:
  cabin-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    volumes:
      - .:/app
    command: ["java", "-jar", "build/libs/CabinJ-1.0-SNAPSHOT.jar"]