version: '3.8'

services:
  cabin-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    command: ["java", "-jar", "cabin-1.0.1.jar"]
    volumes:
      - gradle-cache:/root/.gradle

volumes:
  gradle-cache: